### ISSUE TITLE
Macports #38208 is fixed (RFE: add a "depends_test" type of dependency)

### ISSUE THREAD

**Issue by Russell-Jones-OxPhys** [cooljeanius/Environment-Modules#1]
https://github.com/cooljeanius/Environment-Modules/blob/cd69d551a3800a137ef3622e5904be94c26d8185/MacPorts/sysutils/environment-modules/Portfile#L102
https://trac.macports.org/ticket/38208

**Comment by cooljeanius** [comment]
oh cool I'll have to update it

**Comment by cooljeanius** [comment]
should be fixed now; I haven't actually tested it myself though...

**Comment by Russell-Jones-OxPhys** [comment]
nice, will have a play. have a good xmas 🎅🦌🦌🦌🛷

Russell

________________________________
